#!/bin/sh
#
# A hook script to verify what is about to be committed. Called by "git commit" with no arguments. The hook will exit
# with non-zero status after issuing an appropriate message if it wants to stop the commit.
python .githooks/pre_commit.py
