[installer]
max-workers = 4  # Too many workers will cause Artifactory issues.

[repositories]
ed-vs-framework-pypi-develop.url = "https://artifactory-04.boschdevcloud.com/artifactory/api/pypi/ed-vs-framework-pypi-develop"

[virtualenvs]
create = true
in-project = true
