[BASIC]
device_under_test = TST_PROJECT_NAME.DUT_VARIANT_NAME_1
intensity = SMOKE;OVERNIGHT;WEEKEND;COMPLETE
requirement_source = DEMAND;INITIATIVE
status = RUNABLE;BROKEN;BUG
test_type = FUNCTIONAL;STRESS;ROBUSTNESS

[AUTH]
module = auth_handling.auth.Auth
auth_file_path = ./configurations/accounts.json
;sql_server = rbgswicymon01
;sql_database = DB_USER_MANAGEMENT
;sql_table = GDE-EDVP5

;[DBUS]
;module = dbus_bsh.dbus_logic_front_end.DbusLogicFrontEnd
;uda_name = UDA1:UDA-01
;simulated_devices = 12
;baudrate = 19200
;configuration = Messages.json
;main_node = False

[UR_ROBOT]
module = ur_robot.ur_robot_logic_front_end.URRobotLogicFrontEnd
ur_ip = 192.168.10.150
pc_ip = 192.168.10.100
configuration = ALL.json
#type = RCP4


[IMAGE_SOURCE]
module = image_acquisition.image_acquisition_front_end.ImageSourceFrontEnd
brand_parameters = configurations/components/camera/brand.ini
unique_parameters = configurations/components/camera/unique.ini

[VISION]
module = vision.image_evaluation.evaluator_factory.EvaluatorFactory
configuration = configurations\components\vision\config.ini