[pytest]
python_files = test.py
junit_logging = all
tar_archive = True
addopts = -p no:logging
          --json-report
          --json-report-indent=2
          --json-report-file=results/Reports/bsh_step_logger_test_session_results.json

[additional_artifacts_to_archive]
files = results/Reports/report*.html
        results/Reports/bsh_step_logger_test_session_results.json
        results/pytest.xml
        results/**/all_test_steps*.log
        results/downloaded_artifacts*


[agent]
; where are the tests stored?
test_folder = tests
; where is the test project located?
project_path = .
; how many last builds should be used for the duration estimation
duration_estimation_build_range = 3
; treat all parameterizations of one test as one big test or as individual ones
coarse_grained_tests = True
; maximum number of tests to execute
max_tests = 5000


[XCSF]
histlen = 6
max_pop_size = 2000
