[common]
STR_TEXT_CLASSIFIER = BIRD
STR_TEXT_FILTER = CART
INT_SPEC_HEIGHT_RESOLUTION = 544
STR_TEXT_LOCALIZER = EASY_OCR

[paths]
#LOAD_FILE_FONT = tests/example_images/bshsiglr_v305.ttf
LOAD_FILE_FONT = configurations/components/vision/Neff.ttf
LOAD_JSON_ROI_FILE = tests/example_images/rois.json
LOAD_JSON_DISPLAY_ROI = tests/example_images/rois_display.json


[evaluation]
STR_TEXT_MATCHER = raw

[expert_parameters]
BOOLEAN_BIRD_TEXT_SCORE_NORMALIZATION = true
